name: todolist
description: yet another todo app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: 0.16.1
  meta: ^1.2.4
  provider: ^4.3.3
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.6
  json_annotation: ^3.1.1
  equatable: ^1.2.5
  image_picker: ^0.6.7+22
  flutter_cache_manager: ^2.1.1
  path_provider: ^1.6.27

  flutter_redux: ^0.7.0
  redux_thunk: ^0.3.0

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  firebase_admob: 0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test: ^1.0.2
  test: ^1.15.7
  mockito: ^4.1.4
  build_runner: ^1.11.0
  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/to-do-list.png'

flutter:
  uses-material-design: true
  generate: true
